default_screen: 'first_screen'
base_url: 'https://google.com' #Will redirect to file path of site.html, requires url for browsers
throttle_driver_methods: #Throttle some driver methods
  exists?: 1
  find_element: 2
  navigate: 3
throttle_element_methods:  #Throttle some element methods
  text: 3.5
  click: 4