default_screen: 'first_screen'
base_url: 'https://google.com' #Will change to file path of site.html, not typical implementation
screen_transition_sleep: 1 #Simple sleep when changing screens, nice when you are starting out